- name: Install AD
  hosts: all
  gather_facts: false
  tasks:
    - name: Install AD srvices and features
      win_feature:
        name: AD-Domain-Services
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes 
